version: "3"
services:
  python3:
    restart: always
    build: .
    container_name: "python3"
    working_dir: "/root/"
    # env_file: ./.variables.env
    tty: true
    volumes:
      - ./opt:/root/opt
      - ./sample-files:/root/file
