version: "3"
services:
  python3:
    restart: always
    build: .
    container_name: "python3"
    working_dir: "/root/src"
    # env_file: ./.variables.env
    tty: true
    volumes:
      - ./src:/root/src
      - ./input:/root/input
